name = "BlockCodes"
uuid = "46e897a3-9f4c-46b5-9e27-777297828a13"
authors = ["Chris Winstead"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
