name = "BlockCodes"
uuid = "46e897a3-9f4c-46b5-9e27-777297828a13"
authors = ["Chris Winstead"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GaloisFields = "8d0d7f98-d412-5cd4-8397-071c807280aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
GaloisFields = "1.3.0"
LinearAlgebra = "1.11.0"
Parameters = "0.12.3"
Primes = "0.5.7"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
